environment:
  QT5DIR: C:\Qt\5.7\msvc2015

cache:
  - vcpkg/ -> get-dependencies.ps1

platform:
  - Win32

configuration:
  - Debug
  - Release

before_build:
 - ps: ./get-dependencies.ps1
 - ps: cmake '-H.' -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 14 2015" -Bbuild

build:
 parallel: true
 project: build/PACKAGE.sln
