environment:
  QT5DIR: C:\Qt\5.9.1\msvc2015
  VULKAN_SDK: C:\projects\warzone2100\vcpkg\VulkanSDK\1.0.57.0
  VK_SDK_PATH: C:\projects\warzone2100\vcpkg\VulkanSDK\1.0.57.0

#cache:
#  - vcpkg/ -> get-dependencies.ps1

platform:
  - Win32

configuration:
  - Release

before_build:
 - set PATH=%PATH%;%QT5DIR%\bin;
 - ps: Invoke-WebRequest "https://onedrive.live.com/download?cid=363DD3AAFA342F70&resid=363DD3AAFA342F70%2120519&authkey=AIoZ_CRK7-Ckq9I" -OutFile vcpkg.7z
 - 7z x vcpkg.7z > NUL
 - cmake -H. -Bbuild  -DCMAKE_TOOLCHAIN_FILE=C:\projects\warzone2100\vcpkg\scripts\buildsystems\vcpkg.cmake -G "Visual Studio 14 2015" 

build:
 parallel: true
 project: build/PACKAGE.vcxproj

artifacts:
 - path: build/wz2100-0.1.1-win32.exe
   name: wz2100_installer
