environment:
  QT5DIR: C:\Qt\5.9.1\msvc2015

cache:
  - vcpkg/ -> get-dependencies.ps1

platform:
  - Win32

configuration:
  - Debug
  - Release

before_build:
 - set PATH=%PATH%;%QT5DIR%\bin;
 - ps: ./get-dependencies.ps1
 - ps: mkdir build
 - ps: pushd build
 - ps: cmake -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 14 2015" ..
 - ps: popd

build:
 parallel: true
 project: build/PACKAGE.vcxproj
