environment:
  QT5DIR: C:\Qt\5.9.1\msvc2015

cache:
  - vcpkg/ -> get-dependencies.ps1

platform:
  - Win32

configuration:
  - Debug
  - Release

before_build:
 - set PATH=%PATH%;%QT5DIR%\bin;
 - ps: Invoke-WebRequest https://1drv.ms/u/s!AnAvNPqq0z02gaAnXhCw3qd1HoxP2Q -OutFile vcpkg.7z
 - 7z x vcpkg.7z > NUL
 - cmake -H. -Bbuild  -DCMAKE_TOOLCHAIN_FILE=C:\projects\warzone2100\vcpkg\scripts\buildsystems\vcpkg.cmake -G "Visual Studio 14 2015" 

build:
 parallel: true
 project: build/src/warzone2100.vcxproj
